web/main/forms/login.py
# - *- coding: utf- 8 - *-
from flask_wtf import FlaskForm  # Importa funciones de formulario
from wtforms import PasswordField, SubmitField  # Importa campos
from wtforms.fields.html5 import EmailField  # Importa campos HTML
from wtforms import validators  # Importa validaciones


class LoginForm(FlaskForm):    # nombredelcampo = TipoDeCampo (etiqueta, [validadores])
    email = EmailField('E-mail',
                       [
                           validators.Required(message="E-mail is required, Please complete the field"),
                           validators.Email(message='Format not valid'),
                       ])

    # Definición de campo de contraseña
    password = PasswordField('Password',
                             [
                                 validators.Required(),
                             ])
    # Definición de campo submit
    submit = SubmitField("Login")

web/main/forms/user.py
from flask_wtf import FlaskForm  # Importa funciones de formulario
from wtforms import PasswordField, SubmitField, BooleanField  # Importa campos
from wtforms.fields.html5 import EmailField  # Importa campos HTML
from wtforms import validators  # Importa validaciones


class UserForm(FlaskForm):

    # Definicion de campo Email
    email = EmailField("E-mail", [
        validators.Required(message="E-mail is require"),
        validators.Email(message="Format not valid"),
    ])

    # Definicion de campo Contraseña
    password = PasswordField("Password", [
        validators.Required(),
        # El campo de contraseña debe coincidir con el de confirmar
        validators.EqualTo("confirm", message="Passwords don't match")
    ])

    confirm = PasswordField("Repeat Password")

    admin = BooleanField("Admin?")

    # Definicion de campo Sumbit
    submit = SubmitField("Add")


class UserEdit(FlaskForm):

    # Definicion de campo Email
    email = EmailField("E-mail", [
        validators.Required(message="E-mail is required"),
        validators.Email(message="Format not valid"),
    ])

    # Definicion de campo Admin
    admin = BooleanField("Admin")

    # Definicion de campo Sumbit
    submit = SubmitField("Send")

web/main/routes/home.py
from flask import Blueprint, redirect, url_for
from flask_breadcrumbs import register_breadcrumb


home = Blueprint("home", __name__, url_prefix="/")


@home.route("/")
@register_breadcrumb(home, 'breadcrumbs.', 'Home')
def index():
    return redirect(url_for("main.index"))

web/main/routes/login.py
import json

from flask import Blueprint, current_app, flash, make_response, redirect, url_for, render_template
from flask_breadcrumbs import register_breadcrumb
from flask_login import login_user, logout_user
import requests

from ..forms.login import LoginForm
from .auth import User

log = Blueprint("login", __name__, url_prefix="/")


@log.route("/login", methods=["POST", "GET"])
# @register_breadcrumb(log, ".", 'login')
def login():
    url = current_app.config['API_URL'] + '/auth/login'
    loginForm = LoginForm()

    if loginForm.validate_on_submit():
        # Enviar requests
        data = '{"email":"' + loginForm.email.data + \
            '", "password":"' + loginForm.password.data + '"}'
        r = requests.post(
            current_app.config["API_URL"]+"/auth/login",
            headers={"content-type": "application/json"},
            data=data
        )
        # Si la request se realiza con exito
        if r.status_code == 200:
            # Cargar valores del usuario de la respuesta
            user_data = json.loads(r.text)
            user = User(id=user_data.get("id"), email=user_data.get(
                "email"), admin=user_data.get("admin"))
            # Loguear objeto usuario
            login_user(user)
            # Crear una request de redireccion
            req = make_response(redirect(url_for("main.index")))
            # Setear cookie con el valor del token
            req.set_cookie("access_token", user_data.get(
                "access_token"), httponly=True)
            # Realizar la request
            flash("Logged In", "info")
            return req

        else:
            # Mostrar error de autenticacion
            flash("Incorrect user or password", "danger")

    return render_template("login.html", loginForm=loginForm)


@log.route("/logout")
def logout():
    # Crear una request de redireccion
    req = make_response(redirect(url_for("main.index")))
    # Vaciar cookie
    req.set_cookie("access_token", "", httponly=True)
    # Desloguear usuario
    logout_user()
    # Realizar request
    flash('Logged Out', 'danger')
    return req

web/main/routes/main.py
from flask import Blueprint, render_template
from flask_breadcrumbs import register_breadcrumb


main = Blueprint("main", __name__, url_prefix="/main")


@main.route("/")
# @register_breadcrumb(main, 'breadcrumbs.', 'Home')
def index():
    title = main
    return render_template("home.html", title=title, main=main)

web/main/routes/sensor.py
from flask import Blueprint, render_template, redirect, url_for, flash, current_app, request
from flask_breadcrumbs import register_breadcrumb
import json, requests

from ..forms.sensor import SensorForm, SensorEdit, SensorFilter

from .auth import admin_required
from flask_login import login_required

from ..utilities.functions import sendRequest


sensor = Blueprint("sensor", __name__, url_prefix="/sensor")


@sensor.route("/")
@login_required
@admin_required
@register_breadcrumb(sensor, ".", 'Sensors')
def index():
    filter = SensorFilter(request.args, meta={"csrf": False})
    req = sendRequest(method="get", url="/users", auth=True)
    filter.userId.choices = [
        (int(user["id"]), user["email"]) for user in json.loads(req.text)["Users"]
    ]
    filter.userId.choices.insert(0, [0, "All"])

    data = {}
    # Validamos formulario de filtro
    if filter.validate():
        if filter.userId.data != None and filter.userId.data != 0:
            data["userId"] = filter.userId.data
        if filter.name.data != None:
            data["name"] = filter.name.data
        if filter.status.data:
            data["status"] = filter.status.data
        if filter.active.data:
            data["active"] = filter.active.data
    # Order
    if "sort_by" in request.args:
        data["sort_by"] = request.args.get("sort_by", "")

    req = sendRequest(method="get", url="/sensors", data=json.dumps(data), auth=True)

    if req.status_code == 200:
        sensors = json.loads(req.text)["Sensors"]
        pagination = {}
        pagination["total"] = json.loads(req.text)["total"]
        pagination["pages"] = json.loads(req.text)["pages"]
        pagination["current_page"] = json.loads(req.text)["page"]
        pagination["per_page"] = json.loads(req.text)["per_page"]
        title = "Sensors"
        return render_template("sensors.html", title=title, sensors=sensors, filter=filter, pagination=pagination,)
    else:
        redirect(url_for("sensor.index"))


@sensor.route("/view/<int:id>")
@login_required
@admin_required
@register_breadcrumb(sensor, '.view', 'View')
def view(id):
    req = sendRequest(method="get", url="/sensor/" + str(id), auth=False)
    if (req.status_code == 404):
        flash("Sensor not found", "danger")
        return redirect(url_for("sensor.index"))
    sensor = json.loads(req.text)
    title = "Sensor View"
    return render_template("sensor-view.html", title=title, sensor=sensor)


@sensor.route("/add-sensor", methods=["GET", "POST"])
@login_required
@admin_required
@register_breadcrumb(sensor, ".add", "Add Sensor")
def create():
    form = SensorForm()  # Instanciar formulario
    req = sendRequest(method="get", url="/users", auth=True)
    form.userId.choices=[(int(user["id"]), user["email"]) for user in json.loads(req.text)["Users"]]
    form.userId.choices.insert(0,[0, "Select one User"])
    if form.validate_on_submit():  # Si el formulario ha sido enviado y es valido correctamente
        sensor = {
            "name": form.name.data,
            "ip": form.ip.data,
            "port": form.port.data,
            "status": form.status.data,
            "active": form.active.data,
            "userId": form.userId.data,
        }
        data = json.dumps(sensor)
        req = sendRequest(method="post", url="/sensors", data=data, auth=True)

        return redirect(url_for("sensor.index"))  # Redirecciona a la lista de sensores
    return render_template("add-sensor.html", form=form)


@sensor.route("/edit/<int:id>", methods=["GET", "POST"])
@login_required
@admin_required
@register_breadcrumb(sensor, ".edit", "Edit Sensor")
def edit(id):
    form = SensorEdit()
    req = sendRequest(method="get", url="/users", auth=True)
    form.userId.choices = [(int(user["id"]), user["email"]) for user in json.loads(req.text)["Users"]]
    form.userId.choices.insert(0, [0, "Select one User"])
    if not form.is_submitted():
        req = sendRequest(method="get", url="/sensor/" + str(id), auth=True)
        if (req.status_code == 404):
            flash("Sensor not found", "danger")
            return redirect(url_for("sensor.index"))
        sensor = json.loads(req.text)

    if form.validate_on_submit():
        sensor = {
            "name": form.name.data,
            "ip": form.ip.data,
            "port": form.port.data,
            "status": form.status.data,
            "active": form.active.data,
            "userId": form.userId.data
        }
        data = json.dumps(sensor)
        req = sendRequest(method="put", url="/sensor/" + str(id), data=data, auth=True)
        flash("Sensor has been edited","success")
        return redirect(url_for("sensor.index"))
    else:
        # cargar datos
        form.name.data = sensor["name"]
        form.ip.data = sensor["ip"]
        form.port.data = sensor["port"]
        form.status.data = sensor["status"]
        form.active.data = sensor["active"]
        form.userId.data = sensor["user"]["id"]

    return render_template("edit-sensor.html", form=form, id=id)


@sensor.route('delete/<int:id>')
@login_required
@admin_required
def delete(id):
    req = sendRequest(method="delete", url="/sensor/" + str(id), auth=True)
    flash("Sensor has been deleted", "danger")
    if req.status_code == 409:
        flash(req.text, "danger")
    return redirect(url_for('sensor.index'))


@sensor.route('check/<int:id>')
@login_required
@admin_required
def check(id):
    req = sendRequest(method="get", url="/sensor/check/" + str(id), auth=True)
    return redirect(url_for('sensor.index'))

web/main/routes/unverified_seism.py
from flask import Blueprint, render_template, current_app, redirect, url_for, flash, request
import requests, json
from flask_breadcrumbs import register_breadcrumb
from ..utilities.functions import sendRequest
from ..forms.unverified_seism import UnverifiedSeismEdit, UnverifiedSeismsFilter
from flask_login import login_required


unverified_seism = Blueprint("unverified_seism", __name__, url_prefix="/unverified-seism")


@unverified_seism.route("/")
@login_required
@register_breadcrumb(unverified_seism, '.', 'Unverified Seisms')
def index():
    # Armamos el filtro
    filter = UnverifiedSeismsFilter(request.args, meta={"csrf": False})
    req = sendRequest(method="get", url="/sensors-info")
    filter.sensorId.choices = [
        (int(sensor["id"]), sensor["name"]) for sensor in json.loads(req.text)['Sensors']
    ]
    filter.sensorId.choices.insert(0, [0, "All Sensor"])
    data = {}
    # Aplicamos los filtros
    # Validar formulario de filtro
    if filter.validate():
        if filter.sensorId.data != None and filter.sensorId.data != 0:
            data["sensorId"] = filter.sensorId.data
        # Datetime
        if filter.from_datetime.data and filter.to_datetime.data:
            if filter.from_datetime.data == filter.to_datetime.data:
                data["datetime"] = filter.to_datetime.data.strftime('%Y-%m-%d %H:%M')
        if filter.from_datetime.data != None:
            data["from_date"] = filter.from_datetime.data.strftime('%Y-%m-%d %H:%M')
        if filter.to_datetime.data != None:
            data["to_date"] = filter.to_datetime.data.strftime('%Y-%m-%d %H:%M')

    # Ordenamiento
    if "sort_by" in request.args:
        data["sort_by"] = request.args.get("sort_by", "")

    # Numero de pagina
    if "page" in request.args:
        data["page"] = request.args.get("page", "")
    else:
        if "page" in data:
            del data["page"]

    req = sendRequest(method="get", url="/unverified-seisms", data=json.dumps(data), auth=True)

    if req.status_code == 200:

        unverified_seisms = json.loads(req.text)["Unverified-Seisms"]  # Cargamos los sismos verificados
        # Cargamos los datos de paginacion cantidad de paginas pagina y paginas a ver
        pagination = {}
        pagination["total"] = json.loads(req.text)["total"]
        pagination["pages"] = json.loads(req.text)["pages"]
        pagination["current_page"] = json.loads(req.text)["page"]
        title = "Unverified Seisms List"
        return render_template("unverified-seisms.html", title=title, unverified_seisms=unverified_seisms,
                               filter=filter,
                               pagination=pagination, )
    else:
        redirect(url_for("unverified_seism.index"))

@unverified_seism.route("/view/<int:id>")
@login_required
@register_breadcrumb(unverified_seism, '.view', 'View')
def view(id):
    r = requests.get(current_app.config["API_URL"]+"/unverified-seism/"+str(id),headers={"content-type":"application/json"})
    if (r.status_code == 404):
        return redirect(url_for("unverified_seism.index"))
    unverified_seism = json.loads(r.text)
    title = "Unverified Seism View"
    return render_template("unverified_seism.html", title=title, unverified_seism=unverified_seism)


@unverified_seism.route("/edit/<int:id>", methods=["GET","POST"])
@login_required
@register_breadcrumb(unverified_seism, ".edit", "Edit Unverified Seism")
def edit(id):
    form = UnverifiedSeismEdit()
    if not form.is_submitted():
        req = sendRequest(method="get", url="/unverified-seism/" + str(id), auth=True)
        if (req.status_code == 404):
            flash("Unverified Seism not found","danger")
            return redirect(url_for("unverified_seism.index"))
        unverified_seism = json.loads(req.text)
        form.depth.data = unverified_seism["depth"]
        form.magnitude.data = unverified_seism["magnitude"]
        form.verified.data = unverified_seism["verified"]

    if form.validate_on_submit():
        unverified_seism = {
            "depth": form.depth.data,
            "magnitude": form.magnitude.data,
            "verified": form.verified.data,
        }
        data = json.dumps(unverified_seism)
        req = sendRequest(method="put", url="/unverified-seism/" + str(id), data=data, auth=True)
        flash("Unverified Seism has been edited","success")
        return redirect(url_for("unverified_seism.index"))
    return render_template("edit-unverifiedseism.html", form=form, id=id)


@unverified_seism.route('delete/<int:id>')
#@login_required
def delete(id):
    req = sendRequest(method="delete", url="/unverified-seism/" + str(id), auth=True)
    flash("Unverified Seism has been deleted", "danger")
    return redirect(url_for('unverified_seism.index'))

web/main/routes/user.py
from flask import Blueprint, render_template, redirect, url_for, flash
from flask_breadcrumbs import register_breadcrumb
from ..forms.user_form import UserForm, UserEdit
from ..utilities.functions import sendRequest
from .auth import admin_required

from flask_login import login_required

import json

user = Blueprint("user", __name__, url_prefix="/user")


@user.route("/")
@login_required
@admin_required
@register_breadcrumb(user, '.', 'Users')
def index():
    req = sendRequest(method="get", url="/users", auth=False)
    users = json.loads(req.text)['Users']
    title = "Users List"
    return render_template("users.html", title=title, users=users)  # Mostrar template


@user.route("/add-user", methods=["GET", "POST"])
@login_required
@admin_required
@register_breadcrumb(user, ".add", "Add User")
def create():
    form = UserForm()  # Instanciar formulario
    if form.validate_on_submit():  # Si el formulario ha sido enviado y es valido correctamente
        user = {
            "email": form.email.data,
            "password": form.password.data,
            "admin": form.admin.data
        }
        data = json.dumps(user)
        req = sendRequest(method="post", url="/users", data=data, auth=True)
        return redirect(url_for("user.index")) # Redirecciona a la lista de usuarios
    return render_template("user_form.html", form=form)


@user.route("/edit/<int:id>", methods=["GET","POST"])
@login_required
@admin_required
@register_breadcrumb(user, ".edit", "Edit User")
def edit(id):
    form = UserEdit()
    if not form.is_submitted():
        req = sendRequest(method="get", url="/user/" + str(id), auth=True)
        if req.status_code == 404:
            flash("User not found", "danger")
            return redirect(url_for("user.index"))
        user = json.loads(req.text)
        form.email.data = user["email"]
        form.admin.data = user["admin"]

    if form.validate_on_submit():
        user = {
            "email": form.email.data,
            "admin": form.admin.data
        }
        data = json.dumps(user)
        req = sendRequest(method="put", url="/user/" + str(id), data=data, auth=True)
        flash("User has been edited", "success")
        return redirect(url_for("user.index"))
    return render_template("user-edit.html", form=form, id=id)


@user.route('delete/<int:id>')
@login_required
@admin_required
def delete(id):
    req = sendRequest(method="delete", url="/user/" + str(id), auth=True)
    flash("User has been deleted", "danger")
    return redirect(url_for('user.index'))

web/main/templates/macros.html
{% from "form_macros.html" import show_field, show_submit, show_placeholder %}

{% macro show_unverified_seism(unverified_seism) %}
<tr>
    <th scope="row">{{unverified_seism.id}}</th>
    <td>{{unverified_seism.datetime}}</td>
    <td>{{unverified_seism.sensor.name}}</td>
    <td>{{unverified_seism.magnitude}}</td>
    <td>
      <div class="btn-group" role="group">
        <button type="button" class="btn btn-sm" data-toggle="tooltip" title="view">
          <a href="{{ url_for('unverified_seism.view',id=unverified_seism.id) }}">
              <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-eye-fill" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                    <path d="M10.5 8a2.5 2.5 0 1 1-5 0 2.5 2.5 0 0 1 5 0z"/>
                    <path fill-rule="evenodd" d="M0 8s3-5.5 8-5.5S16 8 16 8s-3 5.5-8 5.5S0 8 0 8zm8 3.5a3.5 3.5 0 1 0 0-7 3.5 3.5 0 0 0 0 7z"/>
              </svg>
          </a>
        </button>

        <button type="button" class="btn btn-sm" data-toggle="tooltip" title="edit">
          <a href="{{ url_for('unverified_seism.edit',id=unverified_seism.id) }}">
              <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-pen-fill" fill="green" xmlns="http://www.w3.org/2000/svg">
                <path fill-rule="evenodd" d="M13.498.795l.149-.149a1.207 1.207 0 1 1 1.707 1.708l-.149.148a1.5 1.5 0 0 1-.059 2.059L4.854 14.854a.5.5 0 0 1-.233.131l-4 1a.5.5 0 0 1-.606-.606l1-4a.5.5 0 0 1 .131-.232l9.642-9.642a.5.5 0 0 0-.642.056L6.854 4.854a.5.5 0 1 1-.708-.708L9.44.854A1.5 1.5 0 0 1 11.5.796a1.5 1.5 0 0 1 1.998-.001z"/>
              </svg>
          </a>
        </button>
         <button type="button" class="btn btn-sm" data-toggle="tooltip" title="delete">
          <a href="{{ url_for('unverified_seism.delete',id=unverified_seism.id) }}">
              <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-trash-fill" fill="red" xmlns="http://www.w3.org/2000/svg">
                  <path fill-rule="evenodd" d="M2.5 1a1 1 0 0 0-1 1v1a1 1 0 0 0 1 1H3v9a2 2 0 0 0 2 2h6a2 2 0 0 0 2-2V4h.5a1 1 0 0 0 1-1V2a1 1 0 0 0-1-1H10a1 1 0 0 0-1-1H7a1 1 0 0 0-1 1H2.5zm3 4a.5.5 0 0 1 .5.5v7a.5.5 0 0 1-1 0v-7a.5.5 0 0 1 .5-.5zM8 5a.5.5 0 0 1 .5.5v7a.5.5 0 0 1-1 0v-7A.5.5 0 0 1 8 5zm3 .5a.5.5 0 0 0-1 0v7a.5.5 0 0 0 1 0v-7z"/>
                </svg>
          </a>
        </button>
      </div>
    </td>
  </tr>
{% endmacro %}

{% macro show_user(user) %}
<tr>
  <th scope="row">{{user.id}}</th>
  <td>{{user.email}}</td>
  <td>{{user.admin}}</td>
    <td>
    <div class="btn-group" role="group">

        <a type="button" class="btn btn-sm" data-toggle="tooltip" title="edit" href="{{ url_for('user.edit',id=user.id) }}">
            <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-pen-fill" fill="green" xmlns="http://www.w3.org/2000/svg">
                <path fill-rule="evenodd" d="M13.498.795l.149-.149a1.207 1.207 0 1 1 1.707 1.708l-.149.148a1.5 1.5 0 0 1-.059 2.059L4.854 14.854a.5.5 0 0 1-.233.131l-4 1a.5.5 0 0 1-.606-.606l1-4a.5.5 0 0 1 .131-.232l9.642-9.642a.5.5 0 0 0-.642.056L6.854 4.854a.5.5 0 1 1-.708-.708L9.44.854A1.5 1.5 0 0 1 11.5.796a1.5 1.5 0 0 1 1.998-.001z"/>
              </svg>
        </a>
        <a type="button" class="btn btn-sm" data-toggle="tooltip" title="delete" href="{{ url_for('user.delete',id=user.id) }}">
            <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-trash-fill" fill="red" xmlns="http://www.w3.org/2000/svg">
                <path fill-rule="evenodd" d="M2.5 1a1 1 0 0 0-1 1v1a1 1 0 0 0 1 1H3v9a2 2 0 0 0 2 2h6a2 2 0 0 0 2-2V4h.5a1 1 0 0 0 1-1V2a1 1 0 0 0-1-1H10a1 1 0 0 0-1-1H7a1 1 0 0 0-1 1H2.5zm3 4a.5.5 0 0 1 .5.5v7a.5.5 0 0 1-1 0v-7a.5.5 0 0 1 .5-.5zM8 5a.5.5 0 0 1 .5.5v7a.5.5 0 0 1-1 0v-7A.5.5 0 0 1 8 5zm3 .5a.5.5 0 0 0-1 0v7a.5.5 0 0 0 1 0v-7z"/>
            </svg>
        </a>
    </div>
    </td>
</tr>
{% endmacro %}

{% macro show_verified_seism(verified_seism) %}
<tr>
    <th scope="row">{{verified_seism.id}}</th>
    <td>{{verified_seism.datetime}}</td>
    <td>{{verified_seism.depth}}</td>
    <td>{{verified_seism.sensor.name}}</td>
    <td>{{verified_seism.magnitude}}</td>
    <td>
      <div class="btn-group" role="group">

          <button type="button" class="btn btn-sm" data-toggle="tooltip" title="view">
              <a href="{{ url_for('verified_seism.view',id=verified_seism.id) }}">
                  <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-eye-fill" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                        <path d="M10.5 8a2.5 2.5 0 1 1-5 0 2.5 2.5 0 0 1 5 0z"/>
                        <path fill-rule="evenodd" d="M0 8s3-5.5 8-5.5S16 8 16 8s-3 5.5-8 5.5S0 8 0 8zm8 3.5a3.5 3.5 0 1 0 0-7 3.5 3.5 0 0 0 0 7z"/>
                  </svg>
              </a>
          </button>
      </div>
    </td>
  </tr>
{% endmacro %}

{% macro show_sensor(sensor) %}
<tr>
  <th scope="row">{{sensor.id}}</th>
  <td>{{sensor.name}}</td>
  <td>{{sensor.status}}</td>
  <td>{{sensor.active}}</td>
  <td>
    {% if sensor.user %}
    {{sensor.user.email}}
    {% endif %}
  </td>
  <td>
    <div class="btn-group" role="group">
      <button type="button" class="btn btn-sm" data-toggle="tooltip" title="view">
          <a href="{{ url_for('sensor.view',id=sensor.id) }}">
            <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-eye-fill" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                        <path d="M10.5 8a2.5 2.5 0 1 1-5 0 2.5 2.5 0 0 1 5 0z"/>
                        <path fill-rule="evenodd" d="M0 8s3-5.5 8-5.5S16 8 16 8s-3 5.5-8 5.5S0 8 0 8zm8 3.5a3.5 3.5 0 1 0 0-7 3.5 3.5 0 0 0 0 7z"/>
                  </svg>
          </a>
      </button>

      <button type="button" class="btn btn-sm" data-toggle="tooltip" title="edit">
          <a href="{{ url_for('sensor.edit',id=sensor.id) }}">
            <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-pen-fill" fill="green" xmlns="http://www.w3.org/2000/svg">
                    <path fill-rule="evenodd" d="M13.498.795l.149-.149a1.207 1.207 0 1 1 1.707 1.708l-.149.148a1.5 1.5 0 0 1-.059 2.059L4.854 14.854a.5.5 0 0 1-.233.131l-4 1a.5.5 0 0 1-.606-.606l1-4a.5.5 0 0 1 .131-.232l9.642-9.642a.5.5 0 0 0-.642.056L6.854 4.854a.5.5 0 1 1-.708-.708L9.44.854A1.5 1.5 0 0 1 11.5.796a1.5 1.5 0 0 1 1.998-.001z"/>
            </svg>
          </a>
      </button>

      <button type="button" class="btn btn-sm" data-toggle="tooltip" title="delete">
          <a href="{{ url_for('sensor.delete',id=sensor.id) }}">
             <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-trash-fill" fill="red" xmlns="http://www.w3.org/2000/svg">
                      <path fill-rule="evenodd" d="M2.5 1a1 1 0 0 0-1 1v1a1 1 0 0 0 1 1H3v9a2 2 0 0 0 2 2h6a2 2 0 0 0 2-2V4h.5a1 1 0 0 0 1-1V2a1 1 0 0 0-1-1H10a1 1 0 0 0-1-1H7a1 1 0 0 0-1 1H2.5zm3 4a.5.5 0 0 1 .5.5v7a.5.5 0 0 1-1 0v-7a.5.5 0 0 1 .5-.5zM8 5a.5.5 0 0 1 .5.5v7a.5.5 0 0 1-1 0v-7A.5.5 0 0 1 8 5zm3 .5a.5.5 0 0 0-1 0v7a.5.5 0 0 0 1 0v-7z"/>
            </svg>
          </a>
      </button>

      <button type="button" class="btn btn-sm" data-toggle="tooltip" title="check status">
          <a href="{{ url_for('sensor.check',id=sensor.id) }}">
            <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-broadcast-pin" fill="yellow" xmlns="http://www.w3.org/2000/svg">
              <path fill-rule="evenodd" d="M3.05 3.05a7 7 0 0 0 0 9.9.5.5 0 0 1-.707.707 8 8 0 0 1 0-11.314.5.5 0 0 1 .707.707zm2.122 2.122a4 4 0 0 0 0 5.656.5.5 0 0 1-.708.708 5 5 0 0 1 0-7.072.5.5 0 0 1 .708.708zm5.656-.708a.5.5 0 0 1 .708 0 5 5 0 0 1 0 7.072.5.5 0 1 1-.708-.708 4 4 0 0 0 0-5.656.5.5 0 0 1 0-.708zm2.122-2.12a.5.5 0 0 1 .707 0 8 8 0 0 1 0 11.313.5.5 0 0 1-.707-.707 7 7 0 0 0 0-9.9.5.5 0 0 1 0-.707zM6 8a2 2 0 1 1 2.5 1.937V15.5a.5.5 0 0 1-1 0V9.937A2 2 0 0 1 6 8z"/>
            </svg>
          </a>
      </button>

    </div>
  </td>
</tr>
{% endmacro %}